version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "127.0.0.1:8010:8010"
    volumes:
        - ./:/app
    stdin_open: true
    tty: true
