[tox]
envlist =
    py311
    report

[testenv]
install_command = pip install {packages}
commands =
    pytest
deps =
    -r{toxinidir}/requirements.txt

[testenv:report]
skipsdist = True
deps = coverage
skip_install = true
commands =
    coverage report
